In [370]:
import pandas as pd

In [372]:
df = pd.read_csv("nba_games.csv", index_col=0)

In [374]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,38.0,72.0,0.528,16.0,37.0,0.432,18.0,21.0,...,26.2,26.8,155.0,123.0,MIA,107,1,2023,2022-11-07,True
1,240.0,240.0,40.0,84.0,0.476,14.0,39.0,0.359,13.0,15.0,...,41.0,37.3,160.0,121.0,POR,110,0,2023,2022-11-07,False
2,240.0,240.0,41.0,78.0,0.526,8.0,24.0,0.333,15.0,19.0,...,28.6,41.1,250.0,125.0,DAL,90,1,2023,2022-12-14,True
3,240.0,240.0,29.0,74.0,0.392,13.0,38.0,0.342,19.0,26.0,...,12.6,33.0,183.0,110.0,CLE,105,0,2023,2022-12-14,False
4,240.0,240.0,37.0,87.0,0.425,7.0,33.0,0.212,32.0,35.0,...,20.0,32.3,226.0,117.0,TOR,126,1,2023,2022-12-07,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14939,240.0,240.0,37.0,88.0,0.420,11.0,29.0,0.379,24.0,27.0,...,25.8,31.0,185.0,126.0,NYK,103,0,2022,2021-11-21,True
14940,240.0,240.0,46.0,102.0,0.451,7.0,35.0,0.200,20.0,27.0,...,37.5,32.8,205.0,120.0,LAL,125,1,2019,2019-02-27,False
14941,240.0,240.0,49.0,94.0,0.521,8.0,25.0,0.320,19.0,31.0,...,69.4,82.7,155.0,122.0,NOP,119,0,2019,2019-02-27,True
14942,240.0,240.0,42.0,90.0,0.467,11.0,30.0,0.367,14.0,17.0,...,50.0,34.5,163.0,122.0,WAS,105,1,2022,2022-01-21,True
14943,240.0,240.0,43.0,85.0,0.506,11.0,33.0,0.333,8.0,10.0,...,18.2,26.1,226.0,122.0,TOR,109,0,2022,2022-01-21,False

In [376]:
df = df.sort_values("date")

In [378]:
df = df.reset_index(drop=True)

In [380]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [382]:
def add_target(team):
    team = team.copy()
    team["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

In [384]:
df[df["team"] == "POR"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
21,240.0,39.0,85.0,0.459,4.0,18.0,0.222,24.0,32.0,0.750,...,29.9,150.0,113.0,LAC,114,0,2017,2016-10-27,False,False
79,240.0,37.0,86.0,0.430,14.0,39.0,0.359,16.0,21.0,0.762,...,37.8,200.0,110.0,GSW,127,0,2017,2016-11-01,False,False
98,265.0,42.0,101.0,0.416,12.0,33.0,0.364,19.0,21.0,0.905,...,26.6,160.0,113.0,PHO,118,1,2017,2016-11-02,False,True
117,240.0,36.0,80.0,0.450,12.0,31.0,0.387,21.0,26.0,0.808,...,33.5,200.0,116.0,DAL,95,1,2017,2016-11-04,True,True
145,240.0,32.0,71.0,0.451,14.0,33.0,0.424,22.0,27.0,0.815,...,31.2,151.0,117.0,MEM,94,1,2017,2016-11-06,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14738,240.0,45.0,93.0,0.484,12.0,33.0,0.364,15.0,25.0,0.600,...,29.9,186.0,131.0,LAC,125,0,2024,2024-03-22,False,False
14756,240.0,43.0,93.0,0.462,10.0,28.0,0.357,15.0,17.0,0.882,...,28.0,138.0,122.0,DEN,114,0,2024,2024-03-23,False,False
14774,240.0,36.0,87.0,0.414,7.0,33.0,0.212,13.0,15.0,0.867,...,34.8,277.0,107.0,HOU,110,1,2024,2024-03-25,False,False
14817,240.0,43.0,85.0,0.506,14.0,31.0,0.452,6.0,10.0,0.600,...,29.2,175.0,115.0,ATL,120,1,2024,2024-03-27,False,False
14842,240.0,35.0,87.0,0.402,5.0,30.0,0.167,7.0,11.0,0.636,...,38.3,186.0,87.0,MIA,142,1,2024,2024-03-29,False,NaN

In [386]:
print(df["team"])

0        GSW
1        CLE
2        NYK
3        SAS
4        TOR
        ...
14939    BOS
14940    DAL
14941    BOS
14942    BOS
14943    DAL
Name: team, Length: 14944, dtype: object

In [388]:
df["target"][pd.isnull(df["target"])] = 2

/var/folders/55/k95kjw9s0n9dccqnfy6097k40000gp/T/ipykernel_41990/1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [390]:
df["target"] = df["target"].astype(int, errors="ignore")

In [392]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,40.0,85.0,0.471,7.0,33.0,0.212,13.0,18.0,0.722,...,36.2,263.0,112.0,SAS,129,0,2017,2016-10-25,False,1
1,240.0,45.0,94.0,0.479,13.0,35.0,0.371,14.0,19.0,0.737,...,36.8,153.0,125.0,NYK,88,0,2017,2016-10-25,True,1
2,240.0,32.0,87.0,0.368,9.0,27.0,0.333,15.0,20.0,0.750,...,36.8,200.0,101.0,CLE,117,1,2017,2016-10-25,False,1
3,240.0,47.0,98.0,0.480,12.0,24.0,0.500,23.0,26.0,0.885,...,31.8,139.0,143.0,GSW,100,1,2017,2016-10-25,True,1
4,240.0,41.0,86.0,0.477,3.0,18.0,0.167,24.0,29.0,0.828,...,39.0,170.0,123.0,DET,91,0,2017,2016-10-26,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14939,240.0,38.0,82.0,0.463,17.0,46.0,0.370,13.0,14.0,0.929,...,40.0,205.0,124.0,DAL,99,1,2024,2024-06-12,True,0
14940,240.0,46.0,91.0,0.505,15.0,37.0,0.405,15.0,22.0,0.682,...,35.9,200.0,138.0,BOS,84,0,2024,2024-06-14,True,0
14941,240.0,29.0,80.0,0.363,14.0,41.0,0.341,12.0,13.0,0.923,...,40.8,212.0,99.0,DAL,122,1,2024,2024-06-14,False,1
14942,240.0,38.0,89.0,0.427,13.0,39.0,0.333,17.0,20.0,0.850,...,54.6,194.0,133.0,DAL,88,0,2024,2024-06-17,True,2
14943,240.0,35.0,78.0,0.449,11.0,37.0,0.297,7.0,13.0,0.538,...,32.3,300.0,110.0,BOS,106,1,2024,2024-06-17,False,2

In [394]:
df["won"].value_counts()

False    7472
True     7472
Name: won, dtype: int64

In [396]:
df["target"].value_counts()

0    7459
1    7455
2      30
Name: target, dtype: int64

In [398]:
nulls = pd.isnull(df)

In [400]:
nulls = nulls.sum()

In [402]:
nulls = nulls[nulls > 0]

In [404]:
nulls

gmsc            14944
+/-             14944
mp_max          14944
mp_max.1        14944
+/-_max            11
gmsc_opp        14944
+/-_opp         14944
mp_max_opp      14944
mp_max_opp.1    14944
+/-_max_opp        11
dtype: int64

In [406]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [408]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [410]:
df = df[valid_columns].copy()

In [412]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,40.0,85.0,0.471,7.0,33.0,0.212,13.0,18.0,0.722,...,36.2,263.0,112.0,SAS,129,0,2017,2016-10-25,False,1
1,240.0,45.0,94.0,0.479,13.0,35.0,0.371,14.0,19.0,0.737,...,36.8,153.0,125.0,NYK,88,0,2017,2016-10-25,True,1
2,240.0,32.0,87.0,0.368,9.0,27.0,0.333,15.0,20.0,0.750,...,36.8,200.0,101.0,CLE,117,1,2017,2016-10-25,False,1
3,240.0,47.0,98.0,0.480,12.0,24.0,0.500,23.0,26.0,0.885,...,31.8,139.0,143.0,GSW,100,1,2017,2016-10-25,True,1
4,240.0,41.0,86.0,0.477,3.0,18.0,0.167,24.0,29.0,0.828,...,39.0,170.0,123.0,DET,91,0,2017,2016-10-26,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14939,240.0,38.0,82.0,0.463,17.0,46.0,0.370,13.0,14.0,0.929,...,40.0,205.0,124.0,DAL,99,1,2024,2024-06-12,True,0
14940,240.0,46.0,91.0,0.505,15.0,37.0,0.405,15.0,22.0,0.682,...,35.9,200.0,138.0,BOS,84,0,2024,2024-06-14,True,0
14941,240.0,29.0,80.0,0.363,14.0,41.0,0.341,12.0,13.0,0.923,...,40.8,212.0,99.0,DAL,122,1,2024,2024-06-14,False,1
14942,240.0,38.0,89.0,0.427,13.0,39.0,0.333,17.0,20.0,0.850,...,54.6,194.0,133.0,DAL,88,0,2024,2024-06-17,True,2
14943,240.0,35.0,78.0,0.449,11.0,37.0,0.297,7.0,13.0,0.538,...,32.3,300.0,110.0,BOS,106,1,2024,2024-06-17,False,2

In [414]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [416]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

In [418]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [420]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [422]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.452381,0.350000,0.473171,0.214286,0.412698,0.201521,0.279070,0.269841,0.675613,...,0.181001,0.815920,0.397727,SAS,0.691489,0.0,2017,2016-10-25,False,1
1,0.0,0.571429,0.500000,0.492683,0.428571,0.444444,0.403042,0.302326,0.285714,0.693116,...,0.188703,0.268657,0.545455,NYK,0.255319,0.0,2017,2016-10-25,True,1
2,0.0,0.261905,0.383333,0.221951,0.285714,0.317460,0.354880,0.325581,0.301587,0.708285,...,0.188703,0.502488,0.272727,CLE,0.563830,1.0,2017,2016-10-25,False,1
3,0.0,0.619048,0.566667,0.495122,0.392857,0.269841,0.566540,0.511628,0.396825,0.865811,...,0.124519,0.199005,0.750000,GSW,0.382979,1.0,2017,2016-10-25,True,1
4,0.0,0.476190,0.366667,0.487805,0.071429,0.174603,0.144487,0.534884,0.444444,0.799300,...,0.216945,0.353234,0.522727,DET,0.287234,0.0,2017,2016-10-26,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14939,0.0,0.404762,0.300000,0.453659,0.571429,0.619048,0.401774,0.279070,0.206349,0.917153,...,0.229782,0.527363,0.534091,DAL,0.372340,1.0,2024,2024-06-12,True,0
14940,0.0,0.595238,0.450000,0.556098,0.500000,0.476190,0.446134,0.325581,0.333333,0.628938,...,0.177150,0.502488,0.693182,BOS,0.212766,0.0,2024,2024-06-14,True,0
14941,0.0,0.190476,0.266667,0.209756,0.464286,0.539683,0.365019,0.255814,0.190476,0.910152,...,0.240051,0.562189,0.250000,DAL,0.617021,1.0,2024,2024-06-14,False,1
14942,0.0,0.404762,0.416667,0.365854,0.428571,0.507937,0.354880,0.372093,0.301587,0.824971,...,0.417202,0.472637,0.636364,DAL,0.255319,0.0,2024,2024-06-17,True,2
14943,0.0,0.333333,0.233333,0.419512,0.357143,0.476190,0.309252,0.139535,0.190476,0.460910,...,0.130937,1.000000,0.375000,BOS,0.446809,1.0,2024,2024-06-17,False,2

In [424]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [426]:
predictors = list(selected_columns[sfs.get_support()])

In [428]:
predictors

['3p%',
 'ft%',
 'pf',
 'orb%',
 'ast%',
 'tov%',
 'usg%',
 'drtg',
 'ft%_max',
 'drb_max',
 'pts_max',
 'gmsc_max',
 'ts%_max',
 'efg%_max',
 'drb%_max',
 'trb%_max',
 'stl%_max',
 'fg_opp',
 'fta_opp',
 'drb%_opp',
 'usg%_opp',
 'ortg_opp',
 'fta_max_opp',
 'blk_max_opp',
 '3par_max_opp',
 'trb%_max_opp',
 'stl%_max_opp',
 'blk%_max_opp',
 'tov%_max_opp',
 'usg%_max_opp']

In [430]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []

    seasons = sorted(data["season"].unique())

    for i in range(start, len(seasons), step):
        season = seasons[i]
        
        train = data[data["season"] < season]
        test = data[data["season"] == season]
        
        model.fit(train[predictors], train["target"])

        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)

        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]

        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [432]:
predictions = backtest(df, rr, predictors)

In [434]:
predictions

       actual  prediction
3894        1           1
3895        0           0
3896        0           1
3897        1           1
3898        1           0
...       ...         ...
14939       0           1
14940       0           1
14941       1           0
14942       2           1
14943       2           1

[11050 rows x 2 columns]

In [436]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["prediction"])

0.5462794918330308

In [438]:
df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.432147
1.0    0.567853
dtype: float64

In [440]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.452381,0.350000,0.473171,0.214286,0.412698,0.201521,0.279070,0.269841,0.675613,...,0.181001,0.815920,0.397727,SAS,0.691489,0.0,2017,2016-10-25,False,1
1,0.0,0.571429,0.500000,0.492683,0.428571,0.444444,0.403042,0.302326,0.285714,0.693116,...,0.188703,0.268657,0.545455,NYK,0.255319,0.0,2017,2016-10-25,True,1
2,0.0,0.261905,0.383333,0.221951,0.285714,0.317460,0.354880,0.325581,0.301587,0.708285,...,0.188703,0.502488,0.272727,CLE,0.563830,1.0,2017,2016-10-25,False,1
3,0.0,0.619048,0.566667,0.495122,0.392857,0.269841,0.566540,0.511628,0.396825,0.865811,...,0.124519,0.199005,0.750000,GSW,0.382979,1.0,2017,2016-10-25,True,1
4,0.0,0.476190,0.366667,0.487805,0.071429,0.174603,0.144487,0.534884,0.444444,0.799300,...,0.216945,0.353234,0.522727,DET,0.287234,0.0,2017,2016-10-26,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14939,0.0,0.404762,0.300000,0.453659,0.571429,0.619048,0.401774,0.279070,0.206349,0.917153,...,0.229782,0.527363,0.534091,DAL,0.372340,1.0,2024,2024-06-12,True,0
14940,0.0,0.595238,0.450000,0.556098,0.500000,0.476190,0.446134,0.325581,0.333333,0.628938,...,0.177150,0.502488,0.693182,BOS,0.212766,0.0,2024,2024-06-14,True,0
14941,0.0,0.190476,0.266667,0.209756,0.464286,0.539683,0.365019,0.255814,0.190476,0.910152,...,0.240051,0.562189,0.250000,DAL,0.617021,1.0,2024,2024-06-14,False,1
14942,0.0,0.404762,0.416667,0.365854,0.428571,0.507937,0.354880,0.372093,0.301587,0.824971,...,0.417202,0.472637,0.636364,DAL,0.255319,0.0,2024,2024-06-17,True,2
14943,0.0,0.333333,0.233333,0.419512,0.357143,0.476190,0.309252,0.139535,0.190476,0.460910,...,0.130937,1.000000,0.375000,BOS,0.446809,1.0,2024,2024-06-17,False,2

In [442]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [444]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.452381,0.350000,0.473171,0.214286,0.412698,0.201521,0.279070,0.269841,0.675613,...,0.111,1.000000,0.181001,0.815920,0.397727,0.691489,0.0,False,GSW,2017
1,0.0,0.571429,0.500000,0.492683,0.428571,0.444444,0.403042,0.302326,0.285714,0.693116,...,0.106,0.475891,0.188703,0.268657,0.545455,0.255319,0.0,True,CLE,2017
2,0.0,0.261905,0.383333,0.221951,0.285714,0.317460,0.354880,0.325581,0.301587,0.708285,...,0.144,0.650943,0.188703,0.502488,0.272727,0.563830,1.0,False,NYK,2017
3,0.0,0.619048,0.566667,0.495122,0.392857,0.269841,0.566540,0.511628,0.396825,0.865811,...,0.072,0.737945,0.124519,0.199005,0.750000,0.382979,1.0,True,SAS,2017
4,0.0,0.476190,0.366667,0.487805,0.071429,0.174603,0.144487,0.534884,0.444444,0.799300,...,0.000,0.211740,0.216945,0.353234,0.522727,0.287234,0.0,True,TOR,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14939,0.0,0.404762,0.300000,0.453659,0.571429,0.619048,0.401774,0.279070,0.206349,0.917153,...,0.082,0.475891,0.229782,0.527363,0.534091,0.372340,1.0,True,BOS,2024
14940,0.0,0.595238,0.450000,0.556098,0.500000,0.476190,0.446134,0.325581,0.333333,0.628938,...,0.164,0.475891,0.177150,0.502488,0.693182,0.212766,0.0,True,DAL,2024
14941,0.0,0.190476,0.266667,0.209756,0.464286,0.539683,0.365019,0.255814,0.190476,0.910152,...,0.125,1.000000,0.240051,0.562189,0.250000,0.617021,1.0,False,BOS,2024
14942,0.0,0.404762,0.416667,0.365854,0.428571,0.507937,0.354880,0.372093,0.301587,0.824971,...,0.056,0.333333,0.417202,0.472637,0.636364,0.255319,0.0,True,BOS,2024
14943,0.0,0.333333,0.233333,0.419512,0.357143,0.476190,0.309252,0.139535,0.190476,0.460910,...,0.031,0.114256,0.130937,1.000000,0.375000,0.446809,1.0,False,DAL,2024

In [446]:
def find_team_averages(team):
    rolling = team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

/var/folders/55/k95kjw9s0n9dccqnfy6097k40000gp/T/ipykernel_41990/4262171003.py:2: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['team'], dtype='object')
  rolling = team.rolling(10).mean()

In [448]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,season
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14939,0.025,0.454762,0.341667,0.481463,0.471429,0.538095,0.370976,0.367442,0.306349,0.802684,...,0.0434,0.1048,0.517610,0.165597,0.466667,0.560227,0.441489,0.4,0.9,2024.0
14940,0.000,0.452381,0.298333,0.519024,0.378571,0.382540,0.396324,0.351163,0.317460,0.732672,...,0.0547,0.0951,0.262788,0.244544,0.431841,0.544318,0.414894,0.5,0.6,2024.0
14941,0.025,0.445238,0.341667,0.469268,0.492857,0.547619,0.385171,0.348837,0.288889,0.813186,...,0.0449,0.1070,0.590566,0.169705,0.498010,0.547727,0.445745,0.5,0.9,2024.0
14942,0.025,0.445238,0.360000,0.454634,0.496429,0.558730,0.379848,0.339535,0.282540,0.810268,...,0.0460,0.1077,0.610587,0.195764,0.487065,0.552273,0.430851,0.4,0.9,2024.0
14943,0.000,0.440476,0.301667,0.500244,0.367857,0.385714,0.383270,0.344186,0.317460,0.705718,...,0.0530,0.0952,0.244130,0.157638,0.510448,0.522727,0.429787,0.5,0.5,2024.0

In [450]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df, df_rolling], axis=1)

In [452]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10
0,0.0,0.452381,0.350000,0.473171,0.214286,0.412698,0.201521,0.279070,0.269841,0.675613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.571429,0.500000,0.492683,0.428571,0.444444,0.403042,0.302326,0.285714,0.693116,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.261905,0.383333,0.221951,0.285714,0.317460,0.354880,0.325581,0.301587,0.708285,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.619048,0.566667,0.495122,0.392857,0.269841,0.566540,0.511628,0.396825,0.865811,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.476190,0.366667,0.487805,0.071429,0.174603,0.144487,0.534884,0.444444,0.799300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14939,0.0,0.404762,0.300000,0.453659,0.571429,0.619048,0.401774,0.279070,0.206349,0.917153,...,0.0434,0.1048,0.517610,0.165597,0.466667,0.560227,0.441489,0.4,0.9,2024.0
14940,0.0,0.595238,0.450000,0.556098,0.500000,0.476190,0.446134,0.325581,0.333333,0.628938,...,0.0547,0.0951,0.262788,0.244544,0.431841,0.544318,0.414894,0.5,0.6,2024.0
14941,0.0,0.190476,0.266667,0.209756,0.464286,0.539683,0.365019,0.255814,0.190476,0.910152,...,0.0449,0.1070,0.590566,0.169705,0.498010,0.547727,0.445745,0.5,0.9,2024.0
14942,0.0,0.404762,0.416667,0.365854,0.428571,0.507937,0.354880,0.372093,0.301587,0.824971,...,0.0460,0.1077,0.610587,0.195764,0.487065,0.552273,0.430851,0.4,0.9,2024.0
14943,0.0,0.333333,0.233333,0.419512,0.357143,0.476190,0.309252,0.139535,0.190476,0.460910,...,0.0530,0.0952,0.244130,0.157638,0.510448,0.522727,0.429787,0.5,0.5,2024.0

In [454]:
df = df.dropna()

In [456]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10
196,0.25,0.523810,0.400000,0.517073,0.178571,0.222222,0.295311,0.627907,0.539683,0.766628,...,0.0600,0.0799,0.410273,0.159050,0.384577,0.442045,0.419149,0.6,0.4,2017.0
213,0.00,0.452381,0.200000,0.607317,0.357143,0.269841,0.513308,0.627907,0.571429,0.716453,...,0.0531,0.0663,0.425052,0.168549,0.412935,0.472727,0.296809,0.5,0.9,2017.0
215,0.00,0.738095,0.500000,0.673171,0.535714,0.365079,0.608365,0.116279,0.095238,0.833139,...,0.0754,0.0620,0.457442,0.176765,0.445771,0.475000,0.444681,0.6,0.6,2017.0
223,0.00,0.285714,0.116667,0.458537,0.250000,0.269841,0.354880,0.558140,0.460317,0.805134,...,0.0784,0.0661,0.425996,0.173042,0.428358,0.454545,0.456383,0.7,0.5,2017.0
227,0.00,0.595238,0.433333,0.570732,0.250000,0.269841,0.354880,0.441860,0.396825,0.730455,...,0.0638,0.0818,0.336478,0.148010,0.387562,0.396591,0.552128,0.5,0.3,2017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14939,0.00,0.404762,0.300000,0.453659,0.571429,0.619048,0.401774,0.279070,0.206349,0.917153,...,0.0434,0.1048,0.517610,0.165597,0.466667,0.560227,0.441489,0.4,0.9,2024.0
14940,0.00,0.595238,0.450000,0.556098,0.500000,0.476190,0.446134,0.325581,0.333333,0.628938,...,0.0547,0.0951,0.262788,0.244544,0.431841,0.544318,0.414894,0.5,0.6,2024.0
14941,0.00,0.190476,0.266667,0.209756,0.464286,0.539683,0.365019,0.255814,0.190476,0.910152,...,0.0449,0.1070,0.590566,0.169705,0.498010,0.547727,0.445745,0.5,0.9,2024.0
14942,0.00,0.404762,0.416667,0.365854,0.428571,0.507937,0.354880,0.372093,0.301587,0.824971,...,0.0460,0.1077,0.610587,0.195764,0.487065,0.552273,0.430851,0.4,0.9,2024.0
14943,0.00,0.333333,0.233333,0.419512,0.357143,0.476190,0.309252,0.139535,0.190476,0.460910,...,0.0530,0.0952,0.244130,0.157638,0.510448,0.522727,0.429787,0.5,0.5,2024.0

In [458]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

/var/folders/55/k95kjw9s0n9dccqnfy6097k40000gp/T/ipykernel_41990/1688004556.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df, "home")
/var/folders/55/k95kjw9s0n9dccqnfy6097k40000gp/T/ipykernel_41990/1688004556.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["team_opp_next"] = add_col(df, "team_opp")
/var/folders/55/k95kjw9s0n9dccqnfy6097k40000gp/T/ipykernel_41990/1688004556.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [460]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10,home_next,team_opp_next,date_next
196,0.25,0.523810,0.400000,0.517073,0.178571,0.222222,0.295311,0.627907,0.539683,0.766628,...,0.159050,0.384577,0.442045,0.419149,0.6,0.4,2017.0,1.0,LAC,2016-11-18
213,0.00,0.452381,0.200000,0.607317,0.357143,0.269841,0.513308,0.627907,0.571429,0.716453,...,0.168549,0.412935,0.472727,0.296809,0.5,0.9,2017.0,1.0,BRK,2016-11-14
215,0.00,0.738095,0.500000,0.673171,0.535714,0.365079,0.608365,0.116279,0.095238,0.833139,...,0.176765,0.445771,0.475000,0.444681,0.6,0.6,2017.0,0.0,MIN,2016-11-13
223,0.00,0.285714,0.116667,0.458537,0.250000,0.269841,0.354880,0.558140,0.460317,0.805134,...,0.173042,0.428358,0.454545,0.456383,0.7,0.5,2017.0,1.0,BRK,2016-11-15
227,0.00,0.595238,0.433333,0.570732,0.250000,0.269841,0.354880,0.441860,0.396825,0.730455,...,0.148010,0.387562,0.396591,0.552128,0.5,0.3,2017.0,0.0,DEN,2016-11-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14939,0.00,0.404762,0.300000,0.453659,0.571429,0.619048,0.401774,0.279070,0.206349,0.917153,...,0.165597,0.466667,0.560227,0.441489,0.4,0.9,2024.0,0.0,DAL,2024-06-14
14940,0.00,0.595238,0.450000,0.556098,0.500000,0.476190,0.446134,0.325581,0.333333,0.628938,...,0.244544,0.431841,0.544318,0.414894,0.5,0.6,2024.0,0.0,BOS,2024-06-17
14941,0.00,0.190476,0.266667,0.209756,0.464286,0.539683,0.365019,0.255814,0.190476,0.910152,...,0.169705,0.498010,0.547727,0.445745,0.5,0.9,2024.0,1.0,DAL,2024-06-17
14942,0.00,0.404762,0.416667,0.365854,0.428571,0.507937,0.354880,0.372093,0.301587,0.824971,...,0.195764,0.487065,0.552273,0.430851,0.4,0.9,2024.0,NaN,None,None
14943,0.00,0.333333,0.233333,0.419512,0.357143,0.476190,0.309252,0.139535,0.190476,0.460910,...,0.157638,0.510448,0.522727,0.429787,0.5,0.5,2024.0,NaN,None,None

In [462]:
df = df.copy()

In [464]:
full = df.merge(df[rolling_cols + ["team_opp_next", "date_next", "team"]], 
                left_on=["team", "date_next"], 
                right_on=["team_opp_next", "date_next"])

In [466]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp_10_y,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,total_opp_10_y,home_opp_10_y,won_10_y,season_10_y,team_opp_next_y,team_y
0,0.25,0.523810,0.400000,0.517073,0.178571,0.222222,0.295311,0.627907,0.539683,0.766628,...,0.394025,0.194737,0.429851,0.502273,0.323404,0.4,0.8,2017.0,SAC,LAC
1,0.00,0.380952,0.283333,0.439024,0.285714,0.285714,0.389100,0.534884,0.523810,0.656943,...,0.410273,0.159050,0.384577,0.442045,0.419149,0.6,0.4,2017.0,LAC,SAC
2,0.00,0.309524,0.400000,0.265854,0.321429,0.317460,0.401774,0.232558,0.285714,0.508751,...,0.560587,0.200513,0.331343,0.345455,0.390426,0.7,0.1,2017.0,ORL,DAL
3,0.00,0.214286,0.300000,0.217073,0.214286,0.222222,0.354880,0.325581,0.285714,0.753792,...,0.273270,0.147882,0.388060,0.420455,0.530851,0.5,0.4,2017.0,NOP,POR
4,0.00,0.595238,0.516667,0.504878,0.464286,0.396825,0.487959,0.441860,0.380952,0.766628,...,0.350000,0.153787,0.332338,0.414773,0.303191,0.6,0.5,2017.0,HOU,UTA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12555,0.00,0.404762,0.266667,0.482927,0.178571,0.301587,0.225602,0.348837,0.365079,0.611435,...,0.491405,0.166752,0.420896,0.568182,0.425532,0.3,0.9,2024.0,DAL,BOS
12556,0.00,0.404762,0.366667,0.402439,0.285714,0.285714,0.389100,0.302326,0.238095,0.854142,...,0.517610,0.165597,0.466667,0.560227,0.441489,0.4,0.9,2024.0,DAL,BOS
12557,0.00,0.404762,0.300000,0.453659,0.571429,0.619048,0.401774,0.279070,0.206349,0.917153,...,0.245283,0.244159,0.412935,0.517045,0.431915,0.5,0.5,2024.0,BOS,DAL
12558,0.00,0.595238,0.450000,0.556098,0.500000,0.476190,0.446134,0.325581,0.333333,0.628938,...,0.590566,0.169705,0.498010,0.547727,0.445745,0.5,0.9,2024.0,DAL,BOS
12559,0.00,0.190476,0.266667,0.209756,0.464286,0.539683,0.365019,0.255814,0.190476,0.910152,...,0.262788,0.244544,0.431841,0.544318,0.414894,0.5,0.6,2024.0,BOS,DAL

In [468]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        SAC             LAC    LAC             SAC  2016-11-18
1        LAC             SAC    SAC             LAC  2016-11-18
2        ORL             DAL    DAL             ORL  2016-11-19
3        NOP             POR    POR             NOP  2016-11-18
4        HOU             UTA    UTA             HOU  2016-11-19
...      ...             ...    ...             ...         ...
12555    DAL             BOS    BOS             DAL  2024-06-12
12556    DAL             BOS    BOS             DAL  2024-06-14
12557    BOS             DAL    DAL             BOS  2024-06-14
12558    DAL             BOS    BOS             DAL  2024-06-17
12559    BOS             DAL    DAL             BOS  2024-06-17

[12560 rows x 5 columns]

In [470]:
removed_columns

['season', 'date', 'won', 'target', 'team', 'team_opp']

In [472]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [474]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_opp_next_x',
 'date_next',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [476]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [478]:
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [480]:
predictors = list(selected_columns[sfs.get_support()])

In [482]:
predictors

['usg%',
 'drb%_max',
 'blk_opp',
 'blk%_opp',
 'usg%_opp',
 'pts_max_opp',
 'trb%_max_opp',
 'tov%_max_opp',
 'ortg_max_opp',
 'ast_10_x',
 'usg%_10_x',
 'drtg_10_x',
 'gmsc_max_10_x',
 '3par_max_10_x',
 'trb_opp_10_x',
 'blk_opp_10_x',
 'usg%_opp_10_x',
 'fg%_max_opp_10_x',
 '3pa_max_opp_10_x',
 'drb_max_opp_10_x',
 'home_next',
 'usg%_10_y',
 '3p%_max_10_y',
 'home_10_y',
 'usg%_opp_10_y',
 'fta_max_opp_10_y',
 'gmsc_max_opp_10_y',
 'stl%_max_opp_10_y',
 'home_opp_10_y',
 'won_10_y']

In [484]:
predictions = backtest(full, rr, predictors)

In [486]:
accuracy_score(predictions["actual"], predictions["prediction"])

0.6214963346269944